name: Build Docker Images
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    paths: [ 'backend/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        working-directory: ./backend
        run: docker build . --file Dockerfile --tag retro:backend-latest
