name: Build Docker Images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: digitalocean
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log into registry ${{ vars.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.API_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push backend image
        id: build-and-push-backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.REGISTRY }}/ahacker-images/retro/backend:latest
      - name: Build and push frontend image
        id: build-and-push-frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.REGISTRY }}/ahacker-images/retro/frontend:latest